INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('1' , '1.' , 'ACTIVO' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('2' , '1.1.' , 'ACTIVOS CIRCULANTES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('3' , '1.1.1.' , 'ACTIVOS DISPONIBLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('4' , '1.1.1.1.' , 'CAJA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('5' , '1.1.1.1.001' , 'CAJA GENERAL' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('6' , '1.1.1.1.002' , 'CAJA CHICA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('7' , '1.1.1.2.' , 'BANCOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('8' , '1.1.1.2.001' , 'Banco g&T Cunta No. 111' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('9' , '1.1.2.' , 'ACTIVOS EXIGIBLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('10' , '1.1.2.1.' , 'CUENTAS POR COBRAR' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('11' , '1.1.2.1.001' , 'CUENTAS POR COBRAR CLIENTES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('12' , '1.1.2.1.002' , 'CUENTAS POR COBRAR EMPLEADOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('13' , '1.1.2.1.003' , 'CUENTAS POR COBRAR OTROS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('14' , '1.1.2.1.004' , 'ANTICIPO A JUSTIFICAR' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('15' , '1.1.3.' , 'ACTIVOS REALIZABLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('16' , '1.1.3.1.' , 'INVENTARIO DE MATERIALES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('17' , '1.1.3.1.001' , 'INV. DE ACCESORIOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('18' , '1.1.3.1.002' , 'INV. DE PAPERIA Y UTILES  DE OFICINA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('19' , '1.1.3.1.003' , 'INV. DE MATERIALES Y LIMPIEZA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('20' , '1.1.3.2.' , 'INVENTARIO DE MERCADERIAS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('21' , '1.1.3.2.001' , 'GRANOS BASICOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('22' , '1.1.4.' , 'OTROS ACTIVOS CIRCULANTES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('23' , '1.1.4.1.' , 'IMPUESTOS ANTICIPADOS Y RETENIDOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('24' , '1.1.4.1.001' , 'IVA CREDITO TRIBUNAL' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('25' , '1.1.4.1.002' , 'ANTICIPO IMPUESTO A LA RENTA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('26' , '1.1.4.1.003' , 'ANTICIPO RETENCION EN LA FUENTE' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('27' , '1.2.' , 'ACTIVOS FIJOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('28' , '1.2.1.' , 'ACTIVOS TANGIBLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('29' , '1.2.1.1.' , 'ACTIVOS DEPRECIABLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('30' , '1.2.1.1.001' , 'INMUEBLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('31' , '1.2.1.1.002' , 'INSTALACIONES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('32' , '1.2.1.2.' , 'ACTIVOS NO DEPRECIABLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('33' , '1.2.1.2.001' , 'TERRENO # 1' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('34' , '1.2.1.3.' , 'DEPRECIACION ACUMULDA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('35' , '1.2.1.3.001' , 'INMUEBLES DEP' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('36' , '1.2.1.3.002' , 'INSTALACIONES DEP' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('37' , '1.2.2.' , 'ACTIVOS INTANGIBLES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('38' , '1.2.2.1.' , 'MARCAS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('39' , '1.2.2.1.001' , 'SERVICIO DE EMPRESA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('40' , '1.2.2.1.002' , 'MARCA DE PRODUCTO' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('41' , '1.2.2.2.' , 'SOFTWARE' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('42' , '1.2.2.2.001' , 'SOFTWARE CONTABLE' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('43' , '1.3.' , 'OTROS ACTIVOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('44' , '1.3.1.' , 'ACTIVOS DIFERIDOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('45' , '1.3.1.1.' , 'GASTOS DE CONSTITUCION' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('46' , '1.3.1.1.001' , 'GASTOS DE CONSTITUCION' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('47' , '1.3.1.2.' , 'GASTOS DE CONSTRUCCION' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('48' , '1.3.2.' , 'OTROS ACTIVOS VARIOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('49' , '1.3.2.1.' , 'DEPOSITOD ENTREGADO EN GARANTIA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('50' , '1.3.2.1.001' , 'INMUEBLES ENTREGADOS EN GARANTIA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('51' , '2.' , 'PASIVO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('52' , '2.1.' , 'PASIVOS A CORTO PLAZO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('53' , '2.1.1.' , 'CUENTAS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('54' , '2.1.1.1.' , 'PROVEEDORES NACIONALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('55' , '2.1.1.1.001' , 'INDUSTRIALES CXP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('56' , '2.1.1.2.' , 'PROVEEDORES LOCALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('57' , '2.1.1.2.001' , 'PROVEEDOR X CXP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('58' , '2.1.1.3.' , 'SERVICIOS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('59' , '2.1.1.3.001' , 'SERV. ENERGIA  CXP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('60' , '2.1.1.3.002' , 'TELEFONO E INTERNET CXP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('61' , '2.1.1.4.' , 'OTRAS CUENTAS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('62' , '2.1.1.4.001' , 'CUENTAS VARIAS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('63' , '2.1.2.' , 'NOMINA POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('64' , '2.1.2.1.' , 'REMUNERACIONES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('65' , '2.1.2.1.001' , 'SUELDOS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('66' , '2.1.2.1.002' , 'DESCUENTOS POR ATRASOS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('67' , '2.1.2.1.003' , 'LIQUIDACIONES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('68' , '2.1.2.2.' , 'INSS E INATEC POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('69' , '2.1.2.2.001' , 'APORTES PERSONAL Y PATRONAL CXP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('70' , '2.1.2.2.002' , 'INATEC POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('71' , '2.1.2.3.' , 'PROVICIONES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('72' , '2.1.2.3.001' , 'DECIMO TERCER MES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('73' , '2.1.2.3.002' , 'VACACIONES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('74' , '2.1.2.3.003' , 'INDEMNIZACIONES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('75' , '2.1.3.' , 'OBLIGACIONES FISCALES POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('76' , '2.1.3.1.' , 'IMPUESTOS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('77' , '2.1.3.1.001' , 'IMPUESTO A LA RENTA POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('78' , '2.1.3.1.002' , 'IVA POR PAGAR (15%)' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('79' , '2.1.3.1.003' , 'IGGS por pgar' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('80' , '2.1.3.1.004' , 'Pasivo Planilla 1' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('81' , '2.1.3.1.005' , 'Pasivo Planilla 2' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('82' , '2.1.3.1.006' , 'Pasivo Planilla 3' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('83' , '2.1.3.1.007' , 'Pasivo Planilla 4' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('84' , '2.1.3.1.008' , 'Pasivo Planilla 5' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('85' , '2.1.3.2.' , 'RETENCIONES FUENTE POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('86' , '2.1.3.2.001' , '2% RET.FTE. SERVICIOS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('87' , '2.1.3.2.002' , '5% RET.FTE. SERVICIO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('88' , '2.1.3.2.003' , '2% RET. FTE DE COMPRAS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('89' , '2.1.3.2.004' , '10% RET.FTE.HONORARIOS PROFESIONALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('90' , '2.1.3.3.' , 'RETENCIONES IVA POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('91' , '2.1.3.3.001' , '15% RET. IVA VENTAS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('92' , '2.1.3.4.' , 'OTROS IMPUESTOS POR PAGAR' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('93' , '2.1.3.5.' , 'RETENCIONES SOBRE SALARIO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('94' , '2.1.3.5.001' , 'RETENCIONES SOBRE SALARIO DGI  XP' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('95' , '2.2.' , 'PASIVOS A LARGO PLAZO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('96' , '2.2.1.' , 'PRESTAMOS A LARGO PLAZO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('97' , '2.2.1.1.' , 'PRESTMOS SOCIOS LARGO PLAZO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('98' , '2.2.1.1.001' , 'R.G. PMO LARGO PLAZO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('99' , '3.' , 'PATRIMONIO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('100' , '3.1.' , 'PATRIMONIO NEGOCIO X' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('101' , '3.1.1.' , 'CAPITAL SOCIAL' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('102' , '3.1.1.1.' , 'CAPITAL PAGADO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('103' , '3.1.1.1.001' , 'CAPITAL NEGOCIO X' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('104' , '3.1.2.' , 'RESERVAS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('105' , '3.1.2.1.' , 'RESERVAS PATRIMONIALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('106' , '3.1.2.1.001' , 'RESERVA FACULTATIVA' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('107' , '3.1.2.1.002' , 'RESERVA DE CAPITAL' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('108' , '3.1.2.1.003' , 'RESERVA LEGAL' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('109' , '3.1.3.' , 'RESULTADOS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('110' , '3.1.3.1.' , 'RESULTADOS ANTERIORES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('111' , '3.1.3.1.001' , 'UTILIDADES ANTERIORES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('112' , '3.1.3.1.002' , 'PERDIDAS ANTERIORES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('113' , '3.1.3.1.003' , 'AMORTIZACION PERDIDAS ANTERIORES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('114' , '3.1.3.2.' , 'RESULTADOS DEL EJERCICIO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('115' , '3.1.3.2.001' , 'UTILIDADES DE EJERCICIO' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('116' , '4.' , 'INGRESOS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('117' , '4.1.' , 'INGRESOS OPERACIONALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('118' , '4.1.1.' , 'VENTAS GENERALES' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('119' , '4.1.1.1.' , 'VENTAS NETAS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('120' , '4.1.1.1.001' , 'VENTAS DE GRANOS BASICOS' , '2' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('121' , '5.' , 'COSTOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('122' , '5.1.' , 'COSTOS OPERACIONALES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('123' , '5.1.1.' , 'COSTO DE VENTA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('124' , '5.1.1.1.' , 'COSTOS DE VENTAS GRANOS BASICO' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('125' , '5.1.1.1.001' , 'COSTO GRANOS BASICO' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('126' , '6.' , 'GASTOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('127' , '6.1.' , 'GASTOS OPERACIONALES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('128' , '6.1.1.' , 'GASTOS DE ADMINISTRACION' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('129' , '6.1.1.1.' , 'SUELDOS Y SIMILARES ADMON' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('130' , '6.1.1.1.001' , 'SUELDOS Y SALARIOS ' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('131' , '6.1.1.1.002' , 'COMPONENTE SALARIAL ADM' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('132' , '6.1.1.1.003' , 'Bonificacion Incentivo' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('133' , '6.1.1.1.004' , 'IGSS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('134' , '6.1.1.1.005' , 'Cuota Laboral' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('135' , '6.1.1.1.006' , 'Cuota Patronal' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('136' , '6.1.1.1.007' , 'Gasto Planilla 1' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('137' , '6.1.1.1.008' , 'Gasto Planilla 2' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('138' , '6.1.1.1.009' , 'Gasto Planilla 3' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('139' , '6.1.1.1.010' , 'Gasto Planilla 4' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('140' , '6.1.1.1.011' , 'Gasto Planilla 5' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('141' , '6.1.1.1.003' , 'HORA EXTRA ADM' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('142' , '6.1.2.' , 'GASTOS DE VENTAS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('143' , '6.1.2.1.' , 'SUELDOS Y SIMILARES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('144' , '6.1.2.1.001' , 'SUELDOS Y SALARIOS DE VENTAS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('145' , '6.1.2.1.002' , 'COMPROBANTE SALARIAL DE VTA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('146' , '6.1.2.1.003' , 'HORAS EXTRAS VTAS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('147' , '6.1.3.' , 'GASTOS FINANCIEROS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('148' , '6.1.3.1.' , 'GASTOS BANCARIOS' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('149' , '6.1.3.1.001' , 'GTOS BANC.X CHEQUERA' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('150' , '6.1.3.1.002' , 'GAST.X SERV.BANC.' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('151' , '6.1.3.1.003' , 'GAST. X DEVALUACION DE LA MONEDA FIN.' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('152' , '6.1.4.' , 'GASTOS GENERALES' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('153' , '6.1.4.1.' , 'MANTENIMIENTO DE MUEBLES Y ENSERES GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('154' , '6.1.4.1.001' , 'MANT. DE MUEBLES GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('155' , '6.1.4.1.002' , 'MANT. DE ENSERES GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('156' , '6.1.4.2.' , 'CONS. DE ENEGIA ELECTRICA GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('157' , '6.1.4.2.01' , 'CONS.ENEGIA ENEL GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('158' , '6.1.4.3.' , 'MOVILIZACIONE LOCALE GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('159' , '6.1.4.3.003' , 'VIATICOS GEN' , '1' , '1');
INSERT INTO `cuentascontables`(`pkId`, `nomenclatura`, `nombre`, `efecto`, `estado`) VALUES ('160' , '6.1.4.3.004' , 'PASAJES AEREOS GEN.' , '1' , '1');
